import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../utils/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.neutral_base_soft,
        paddingHorizontal: SIZES.padding * 2.5,
        paddingTop: SIZES.padding * 2.5,
        paddingBottom: SIZES.padding,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
        marginTop: 55,
        marginHorizontal: 18,
        paddingHorizontal: 0,
    },
    backButton: {
        padding: 12,
        marginRight: 15,
        backgroundColor: COLORS.white,
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    backIcon: {
        width: 24,
        height: 24,
        tintColor: COLORS.neutral_base_dark,
    },
    headerTitle: {
        fontSize: 24,
        fontFamily: 'Baloo2-Bold',
        color: COLORS.neutral_base_dark,
        flex: 1,
    },
    searchBar: {
        height: 50,
        backgroundColor: COLORS.white,
        borderRadius: 25,
        paddingHorizontal: 25,
        marginBottom: 30,
        marginHorizontal: 18,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    listContainer: {
        paddingBottom: 20,
    },
    userItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: COLORS.white,
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 20,
        marginBottom: 15,
        marginHorizontal: 18,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
    },
    profilePic: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        marginRight: 12,
        borderWidth: 2,
        borderColor: COLORS.primary,
    },
    username: {
        fontSize: 15,
        fontFamily: 'Baloo2-SemiBold',
        color: COLORS.neutral_base_dark,
    },
    followButton: {
        backgroundColor: COLORS.bright_button_color,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        shadowColor: COLORS.bright_button_color,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        elevation: 5,
    },
    followingButton: {
        backgroundColor: COLORS.neutral_base_soft,
    },
    followButtonText: {
        color: COLORS.white,
        fontSize: 14,
        fontFamily: 'Poppins-SemiBold',
    },
    followingButtonText: {
        color: COLORS.neutral_base_dark,
    },
    errorText: {
        color: COLORS.error,
        textAlign: 'center',
        marginTop: 20,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
        color: COLORS.neutral_base_dark,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#F8F9FA',
        borderRadius: 30,
        padding: 25,
        width: '85%',
        maxWidth: 320,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4.65,
        elevation: 8,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.1)',
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 25,
        padding: 15,
        backgroundColor: COLORS.white,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalProfilePic: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 3,
        borderColor: COLORS.bright_button_color,
        marginBottom: 10,
    },
    modalUsername: {
        fontSize: 22,
        fontFamily: 'Baloo2-Bold',
        color: COLORS.neutral_base_dark,
        textAlign: 'center',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        marginBottom: 25,
        padding: 15,
        backgroundColor: COLORS.white,
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statIcon: {
        width: 32,
        height: 32,
        marginBottom: 8,
    },
    statValue: {
        fontSize: 24,
        fontFamily: 'Baloo2-Bold',
        color: COLORS.bright_button_color,
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 14,
        fontFamily: 'Poppins-Regular',
        color: COLORS.neutral_base_dark,
    },
    statDivider: {
        width: 1,
        height: 60,
        backgroundColor: COLORS.neutral_base_soft,
        marginHorizontal: 10,
    },
    closeButton: {
        backgroundColor: COLORS.bright_button_color,
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 25,
        alignSelf: 'center',
        shadowColor: COLORS.bright_button_color,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        elevation: 5,
    },
    closeButtonText: {
        color: COLORS.white,
        fontSize: 16,
        fontFamily: 'Poppins-SemiBold',
    },
    friendLabel: {
        fontSize: 14,
        fontFamily: 'Poppins-Regular',
        color: COLORS.neutral_base_dark,
        marginTop: 2,
        opacity: 0.8,
    },
}); 