import { StyleSheet } from 'react-native';
import { COLORS, SIZES } from '../utils/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.neutral_base_soft,
        paddingHorizontal: SIZES.padding * 2.5,
        paddingTop: SIZES.padding * 2.5,
        paddingBottom: SIZES.padding,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 30,
        marginTop: 55,
        marginHorizontal: 18,
        paddingHorizontal: 0,
    },
    backButton: {
        padding: 12,
        marginRight: 15,
        backgroundColor: COLORS.white,
        borderRadius: 15,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    backIcon: {
        width: 24,
        height: 24,
        tintColor: COLORS.neutral_base_dark,
    },
    headerTitle: {
        fontSize: 24,
        fontFamily: 'Baloo2-Bold',
        color: COLORS.neutral_base_dark,
        flex: 1,
    },
    searchBar: {
        height: 50,
        backgroundColor: COLORS.white,
        borderRadius: 25,
        paddingHorizontal: 25,
        marginBottom: 30,
        marginHorizontal: 18,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    listContainer: {
        paddingBottom: 20,
    },
    userItem: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: COLORS.white,
        paddingVertical: 12,
        paddingHorizontal: 15,
        borderRadius: 20,
        marginBottom: 15,
        marginHorizontal: 18,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3.84,
        elevation: 5,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 10,
    },
    profilePic: {
        width: 45,
        height: 45,
        borderRadius: 22.5,
        marginRight: 12,
        borderWidth: 2,
        borderColor: COLORS.primary,
    },
    username: {
        fontSize: 15,
        fontFamily: 'Baloo2-SemiBold',
        color: COLORS.neutral_base_dark,
    },
    followButton: {
        backgroundColor: COLORS.bright_button_color,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        shadowColor: COLORS.bright_button_color,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        elevation: 5,
    },
    followingButton: {
        backgroundColor: COLORS.neutral_base_soft,
    },
    followButtonText: {
        color: COLORS.white,
        fontSize: 14,
        fontFamily: 'Poppins-SemiBold',
    },
    followingButtonText: {
        color: COLORS.neutral_base_dark,
    },
    errorText: {
        color: COLORS.error,
        textAlign: 'center',
        marginTop: 20,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        fontFamily: 'Poppins-Regular',
        color: COLORS.neutral_base_dark,
    },
}); 